apiVersion: v1
kind: Service
metadata:
  name: monitoring-service
  namespace: monitoring-platform
spec:
  selector:
    app: monitoring-service
  ports:
    - name: http
      port: 8282
      targetPort: 8282
  type: ClusterIP