services:

  monitoring-service:
    image: monitoring/monitoring-service:0.0.1
    container_name: monitoring-service
    ports:
      - "8282:8282"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - monitoring-platform
networks:
  monitoring-platform:
    external: true
    name: monitoring-platform